### ISSUE TITLE
[BUG] ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers'

### ISSUE THREAD

**Issue by rdbis** [rdbis/twint#1]
# [BUG] ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers'

Environment:
- [] Python version is 3.10.8;
- [] Windows 11
- [] git clone https://github.com/rdbis/twint.git

### Command Ran
python3 test.py

### Description of Issue
When running test.py the following error can be seen:
\twint-github\venv\Scripts\python.exe /twint-github/test.py
Traceback (most recent call last):
  File "\twint-github\test.py", line 1, in <module>
    import twint
  File "\twint-github\twint\__init__.py", line 14, in <module>
    from . import run
  File "\twint-github\twint\run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "\twint-github\twint\get.py", line 12, in <module>
    from aiohttp_socks import ProxyConnector, ProxyType
  File "\twint-github\venv\lib\site-packages\aiohttp_socks\__init__.py", line 5, in <module>
    from .connector import (
  File "\twint-github\venv\lib\site-packages\aiohttp_socks\connector.py", line 8, in <module>
    from aiohttp.helpers import CeilTimeout  # noqa
ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (\twint-github\venv\lib\site-packages\aiohttp\helpers.py)

**Comment by rdbis** [comment]
package compatibility error - using old, obsolete version of aiohttp_socks
