### ISSUE TITLE
[BUG] twint.token.RefreshTokenException: Could not find the Guest token in HTML

### ISSUE THREAD

**Issue by rdbis** [rdbis/twint#3]
- [] Python version is 3.10.8
- [] master
- [] windows 11

### Command Ran
python3 test.py 
results in the following error:
[+] Beginning vanilla test in <function Profile at 0x000002C6CCE5A950>
Traceback (most recent call last):
  File "C:\Users\XX\twint-github\test.py", line 92, in <module>
    main()
  File "C:\Users\XX\twint-github\test.py", line 78, in main
    test(c, run)
  File "C:\Users\XX\twint-github\test.py", line 11, in test_reg
    run(c)
  File "C:\Users\XX\twint-github\twint\run.py", line 398, in Profile
    run(config)
  File "C:\Users\XX\twint-github\twint\run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "C:\Users\XX\twint-github\twint\run.py", line 36, in __init__
    self.token.refresh()
  File "C:\Users\XX\twint-github\twint\token.py", line 69, in refresh
    raise RefreshTokenException('Could not find the Guest token in HTML')
twint.token.RefreshTokenException: Could not find the Guest token in HTML

**Comment by rdbis** [comment]
no repro so far, sporadic error

**Comment by rdbis** [comment]
afer fix for ""[BUG] SearchProfile (twitter.run.Profile) uses obsolete API (timeline) #5" - no repro.
